<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitPhotos
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OCA\\Photos\\' => 11,
        ),
        'H' => 
        array (
            'Hexogen\\KDTree\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\Photos\\' => 
        array (
            0 => __DIR__ . '/..' . '/../lib',
        ),
        'Hexogen\\KDTree\\' => 
        array (
            0 => __DIR__ . '/..' . '/hexogen/kdtree/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Hexogen\\KDTree\\Exception\\ValidationException' => __DIR__ . '/..' . '/hexogen/kdtree/src/Exception/ValidationException.php',
        'Hexogen\\KDTree\\FSKDTree' => __DIR__ . '/..' . '/hexogen/kdtree/src/FSKDTree.php',
        'Hexogen\\KDTree\\FSNode' => __DIR__ . '/..' . '/hexogen/kdtree/src/FSNode.php',
        'Hexogen\\KDTree\\FSTreePersister' => __DIR__ . '/..' . '/hexogen/kdtree/src/FSTreePersister.php',
        'Hexogen\\KDTree\\Interfaces\\ItemFactoryInterface' => __DIR__ . '/..' . '/hexogen/kdtree/src/Interfaces/ItemFactoryInterface.php',
        'Hexogen\\KDTree\\Interfaces\\ItemInterface' => __DIR__ . '/..' . '/hexogen/kdtree/src/Interfaces/ItemInterface.php',
        'Hexogen\\KDTree\\Interfaces\\ItemListInterface' => __DIR__ . '/..' . '/hexogen/kdtree/src/Interfaces/ItemListInterface.php',
        'Hexogen\\KDTree\\Interfaces\\KDTreeInterface' => __DIR__ . '/..' . '/hexogen/kdtree/src/Interfaces/KDTreeInterface.php',
        'Hexogen\\KDTree\\Interfaces\\NodeInterface' => __DIR__ . '/..' . '/hexogen/kdtree/src/Interfaces/NodeInterface.php',
        'Hexogen\\KDTree\\Interfaces\\PointInterface' => __DIR__ . '/..' . '/hexogen/kdtree/src/Interfaces/PointInterface.php',
        'Hexogen\\KDTree\\Interfaces\\SearchAbstract' => __DIR__ . '/..' . '/hexogen/kdtree/src/Interfaces/SearchAbstract.php',
        'Hexogen\\KDTree\\Interfaces\\TreePersisterInterface' => __DIR__ . '/..' . '/hexogen/kdtree/src/Interfaces/TreePersisterInterface.php',
        'Hexogen\\KDTree\\Item' => __DIR__ . '/..' . '/hexogen/kdtree/src/Item.php',
        'Hexogen\\KDTree\\ItemFactory' => __DIR__ . '/..' . '/hexogen/kdtree/src/ItemFactory.php',
        'Hexogen\\KDTree\\ItemList' => __DIR__ . '/..' . '/hexogen/kdtree/src/ItemList.php',
        'Hexogen\\KDTree\\KDTree' => __DIR__ . '/..' . '/hexogen/kdtree/src/KDTree.php',
        'Hexogen\\KDTree\\NearestSearch' => __DIR__ . '/..' . '/hexogen/kdtree/src/NearestSearch.php',
        'Hexogen\\KDTree\\Node' => __DIR__ . '/..' . '/hexogen/kdtree/src/Node.php',
        'Hexogen\\KDTree\\Point' => __DIR__ . '/..' . '/hexogen/kdtree/src/Point.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitPhotos::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitPhotos::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitPhotos::$classMap;

        }, null, ClassLoader::class);
    }
}
