<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Hexogen\\KDTree\\Exception\\ValidationException' => $vendorDir . '/hexogen/kdtree/src/Exception/ValidationException.php',
    'Hexogen\\KDTree\\FSKDTree' => $vendorDir . '/hexogen/kdtree/src/FSKDTree.php',
    'Hexogen\\KDTree\\FSNode' => $vendorDir . '/hexogen/kdtree/src/FSNode.php',
    'Hexogen\\KDTree\\FSTreePersister' => $vendorDir . '/hexogen/kdtree/src/FSTreePersister.php',
    'Hexogen\\KDTree\\Interfaces\\ItemFactoryInterface' => $vendorDir . '/hexogen/kdtree/src/Interfaces/ItemFactoryInterface.php',
    'Hexogen\\KDTree\\Interfaces\\ItemInterface' => $vendorDir . '/hexogen/kdtree/src/Interfaces/ItemInterface.php',
    'Hexogen\\KDTree\\Interfaces\\ItemListInterface' => $vendorDir . '/hexogen/kdtree/src/Interfaces/ItemListInterface.php',
    'Hexogen\\KDTree\\Interfaces\\KDTreeInterface' => $vendorDir . '/hexogen/kdtree/src/Interfaces/KDTreeInterface.php',
    'Hexogen\\KDTree\\Interfaces\\NodeInterface' => $vendorDir . '/hexogen/kdtree/src/Interfaces/NodeInterface.php',
    'Hexogen\\KDTree\\Interfaces\\PointInterface' => $vendorDir . '/hexogen/kdtree/src/Interfaces/PointInterface.php',
    'Hexogen\\KDTree\\Interfaces\\SearchAbstract' => $vendorDir . '/hexogen/kdtree/src/Interfaces/SearchAbstract.php',
    'Hexogen\\KDTree\\Interfaces\\TreePersisterInterface' => $vendorDir . '/hexogen/kdtree/src/Interfaces/TreePersisterInterface.php',
    'Hexogen\\KDTree\\Item' => $vendorDir . '/hexogen/kdtree/src/Item.php',
    'Hexogen\\KDTree\\ItemFactory' => $vendorDir . '/hexogen/kdtree/src/ItemFactory.php',
    'Hexogen\\KDTree\\ItemList' => $vendorDir . '/hexogen/kdtree/src/ItemList.php',
    'Hexogen\\KDTree\\KDTree' => $vendorDir . '/hexogen/kdtree/src/KDTree.php',
    'Hexogen\\KDTree\\NearestSearch' => $vendorDir . '/hexogen/kdtree/src/NearestSearch.php',
    'Hexogen\\KDTree\\Node' => $vendorDir . '/hexogen/kdtree/src/Node.php',
    'Hexogen\\KDTree\\Point' => $vendorDir . '/hexogen/kdtree/src/Point.php',
);
